"""
Marginalia — app.py  v1.4.1
Flask backend. Run via bootstrap.command or: python app.py
All API keys loaded from setup.env — edit that file, never touch this one.
"""

import os
import io
import csv
import json
import uuid
import time as _time
import threading
import webbrowser
from pathlib import Path
from datetime import datetime

from flask import Flask, request, jsonify, render_template, send_from_directory, Response, stream_with_context
from dotenv import load_dotenv

# ─── Paths ────────────────────────────────────────────────────────────────────
from utils.paths import (
    APP_ROOT, CANONICAL_DIR, REFERENCES_DIR, SESSIONS_DIR,
    CAPTURES_DIR, EXPORTS_DIR, PROJECTS_DIR, WRITING_DIR, SETTINGS_PATH, BROADCAST_URL
)

# ─── Bootstrap — load setup.env (visible), fall back to .env (legacy) ────────
setup_env = APP_ROOT / "setup.env"
dot_env   = APP_ROOT / ".env"
if setup_env.exists():
    load_dotenv(setup_env)
elif dot_env.exists():
    load_dotenv(dot_env)

KEYS = {
    "gemini":     os.getenv("GOOGLE_API_KEY"),
    "anthropic":  os.getenv("ANTHROPIC_API_KEY"),
    "openai":     os.getenv("OPENAI_API_KEY"),
}

OLLAMA_BASE = os.getenv("OLLAMA_HOST", "http://127.0.0.1:11434")

# Research PDF folder — configurable in setup.env, defaults to ~/Documents/Research/PDFs/
# Why configurable: researchers may store PDFs on external drives (Vault SSD),
# network shares, or non-standard locations. Hardcoding ~/Documents/Research/PDFs/
# was removed in v0.9.8 to avoid assuming Mac filesystem conventions for
# a tool intended for distribution to other researchers.
_research_pdf_path = os.getenv("RESEARCH_PDF_PATH", "")
RESEARCH_PDF_DIR = Path(_research_pdf_path).expanduser() if _research_pdf_path else Path.home() / "Documents" / "Research" / "PDFs"

# If OLLAMA_MODELS_PATH is set in setup.env, inject it into the environment
# so Ollama finds models on external drives (e.g. Vault SSD on Mac Mini)
_ollama_models_path = os.getenv("OLLAMA_MODELS_PATH", "")
if _ollama_models_path:
    os.environ["OLLAMA_MODELS"] = _ollama_models_path

for d in [REFERENCES_DIR, SESSIONS_DIR, CAPTURES_DIR, EXPORTS_DIR, PROJECTS_DIR, WRITING_DIR, APP_ROOT / "db", APP_ROOT / "canonical" / "notes"]:
    d.mkdir(parents=True, exist_ok=True)

NOTES_DIR = APP_ROOT / "canonical" / "notes"

# ─── Version ──────────────────────────────────────────────────────────────────
APP_VERSION = "1.4.1"

# ─── Session lock ─────────────────────────────────────────────────────────────
# One active research session at a time — across tabs and devices.
# Physical analogy: two notebooks open, but you only write in one.
# Lock is in-memory only — survives neither Flask restart nor power cycle.
# Heartbeat must arrive every 30s or lock is considered abandoned (45s timeout).
# Read operations (references, notes, intelligence browse) are never locked.
# Write operations (prompt, ingest, save & break) check the lock before proceeding.
_session_lock = {
    "tab_id":     None,   # UUID generated by the claiming tab
    "claimed_at": None,   # epoch float
    "last_beat":  None,   # epoch float — updated by heartbeat
}
_session_lock_mutex = threading.Lock()
SESSION_LOCK_TIMEOUT = 45  # seconds — dead tab expiry

# ─── App ──────────────────────────────────────────────────────────────────────
app = Flask(__name__, template_folder="templates", static_folder="static")
app.config["MAX_CONTENT_LENGTH"] = 16 * 1024 * 1024

# ─── Token tracking ───────────────────────────────────────────────────────────
anthropic_tokens = {"input": 0, "output": 0}
_tokens_lock = threading.Lock()

def estimate_anthropic_cost(input_tokens: int, output_tokens: int) -> float:
    return (input_tokens / 1_000_000 * 0.80) + (output_tokens / 1_000_000 * 4.00)

# ─── Settings ─────────────────────────────────────────────────────────────────
def load_settings():
    if SETTINGS_PATH.exists():
        return json.loads(SETTINGS_PATH.read_text())
    return {}

def save_settings(data):
    SETTINGS_PATH.write_text(json.dumps(data, indent=2))

# ─── Canonical file helpers ───────────────────────────────────────────────────
def write_canonical_reference(data: dict) -> Path:
    """
    Write a reference as a plain markdown file with YAML frontmatter.

    Why markdown, not a database:
    - Human-readable and editable with any text editor
    - Researcher owns the files — not locked to Marginalia
    - Works with Obsidian, VS Code, git diff, grep
    - Survives software rot: markdown will be readable in 20 years
    - The instrument is a guest in the researcher's files, not the landlord

    File naming: LastName_Year_slug.md
    The slug is derived from the first 3 words of the title.
    This makes files sortable, scannable, and meaningful at a glance.
    """
    ref_id = data.get("id") or str(uuid.uuid4())
    data["id"] = ref_id
    first_author = data.get("authors", "Unknown").split(";")[0].split(",")[0].strip()
    year = data.get("year", "0000")
    title_slug = "-".join(data.get("title", "untitled").lower().split()[:3])
    title_slug = "".join(c for c in title_slug if c.isalnum() or c == "-")
    filename = f"{first_author}_{year}_{title_slug}.md"

    annotation   = data.get("annotation") or "<!-- AI annotation — run Generate to populate -->"
    user_notes   = data.get("user_notes") or "<!-- Your own critical reading of this source -->"
    argument     = data.get("argument_connection") or "<!-- How does this source support, complicate, or challenge your research argument? -->"

    tags = data.get("tags", "")
    if not tags and data.get("themes", ""):
        raw = data.get("themes", "")
        parts = [p.strip() for p in raw.split(",") if p.strip()]
        if all(len(p.split()) <= 4 for p in parts):
            tags = raw

    themes_raw = data.get("themes", "")
    if themes_raw and themes_raw != tags:
        theme_lines = "\n".join(
            ("- " + t.strip()) if not t.strip().startswith("-") else t.strip()
            for t in themes_raw.split(",") if t.strip()
        )
    else:
        theme_lines = "<!-- Conceptual themes — full phrases, one per line as: - theme -->"

    connections_raw = data.get("connections", "")
    if connections_raw:
        conn_lines = connections_raw
    else:
        conn_lines = "<!-- Connections to writing/projects: name | note -->"

    canonical = f"""---
id: {ref_id}
title: {data.get("title", "")}
authors: {data.get("authors", "")}
year: {data.get("year", "")}
source_type: {data.get("source_type", "other")}
url_doi: {data.get("url_doi", "")}
verification_status: {data.get("verification_status", "surfaced")}
physical_holding: {data.get("physical_holding", "none")}
holding_location: {data.get("holding_location", "")}
tags: {tags}
created_at: {datetime.now(datetime.UTC).isoformat()}
updated_at: {datetime.now(datetime.UTC).isoformat()}
---

## Themes
{theme_lines}

## Connections
{conn_lines}

## Annotation
{annotation}

## Argument Connection
{argument}

## Your Notes
{user_notes}
"""
    filepath = REFERENCES_DIR / filename

    # De-dupe check: warn if a file with this name already exists
    # (same first author + year + title slug = likely duplicate)
    if filepath.exists():
        # Append a short uuid fragment to avoid silent overwrite
        dedup_suffix = str(uuid.uuid4())[:6]
        filename     = f"{first_author}_{year}_{title_slug}_{dedup_suffix}.md"
        filepath     = REFERENCES_DIR / filename
        import logging
        logging.warning(f"Duplicate reference detected — saving as {filename}")

    filepath.write_text(canonical, encoding="utf-8")
    return filepath


def write_canonical_session(prompt: str, responses: dict, synthesis: str = "", project: str = "", notes: str = "", writing: str = "") -> Path:
    """
    Write a session as a plain markdown file.

    Sessions are the researcher's thinking record — not a log, not telemetry.
    They are meant to be read, annotated, and connected to other canonical files.
    The markdown format means a researcher can open any session file and read it
    as a document, not decode it as a database record.

    The `project` and `notes` fields in frontmatter enable the Intelligence tab
    to filter sessions by project scope and surface connections to deep read notes.
    The `prompt_label` is the first 80 characters of the prompt — used as a
    display label in the Intelligence tab without loading the full session body.
    """
    session_id    = str(uuid.uuid4())
    timestamp     = datetime.now(datetime.UTC).strftime("%Y-%m-%d_%H-%M")
    filename      = f"session_{timestamp}.md"
    prompt_label  = prompt.strip().replace("\n", " ")[:80]
    response_blocks = "\n\n".join(
        f"### {model.capitalize()}\n{text}" for model, text in responses.items() if text
    )
    synth_block = synthesis if synthesis else "<!-- Add synthesis notes here -->"
    canonical = f"""---
id: {session_id}
created_at: {datetime.now(datetime.UTC).isoformat()}
models: {list(responses.keys())}
project: {project}
writing: {writing}
notes: {notes}
prompt_label: {prompt_label}
---

## Prompt
{prompt}

## Responses
{response_blocks}

## Synthesis
{synth_block}
"""
    filepath = SESSIONS_DIR / filename
    filepath.write_text(canonical, encoding="utf-8")
    return filepath


def read_all_references() -> list:
    refs = []
    for filepath in sorted(REFERENCES_DIR.glob("*.md")):
        try:
            text = filepath.read_text(encoding="utf-8")
            if text.startswith("---"):
                parts = text.split("---", 2)
                if len(parts) >= 3:
                    meta = {}
                    for line in parts[1].strip().splitlines():
                        if ": " in line:
                            k, v = line.split(": ", 1)
                            meta[k.strip()] = v.strip()
                    meta["_filename"] = filepath.name
                    body = parts[2]
                    def extract_section(body, heading):
                        if "## " + heading in body:
                            raw = body.split("## " + heading)[1].split("\n## ")[0].strip()
                            if raw and not raw.startswith("<!--"):
                                return raw
                        return ""
                    meta["annotation"]          = extract_section(body, "Annotation")
                    meta["argument_connection"] = extract_section(body, "Argument Connection")
                    meta["user_notes"]           = extract_section(body, "Your Annotation")
                    meta["themes_body"]          = extract_section(body, "Themes")
                    meta["connections"]          = extract_section(body, "Connections")

                    if not meta["themes_body"] and meta.get("themes"):
                        meta["themes_body"] = meta["themes"]
                    meta["tags_list"]  = [t.strip() for t in meta.get("tags","").split(",") if t.strip()]
                    meta["theme_list"] = [ln.lstrip("- ").strip() for ln in (meta["themes_body"] or "").splitlines() if ln.strip() and not ln.strip().startswith("<!--")]
                    meta["conn_list"]  = [ln.strip() for ln in (meta["connections"] or "").splitlines() if ln.strip() and not ln.strip().startswith("<!--")]
                    status_hist = extract_section(body, "Status History")
                    if status_hist:
                        lines = [l.strip() for l in status_hist.splitlines() if l.strip() and not l.startswith("<!--")]
                        meta["last_status_change"] = lines[-1].lstrip("- ").strip() if lines else ""
                    else:
                        meta["last_status_change"] = ""
                    edit_hist = extract_section(body, "Edit History")
                    if edit_hist:
                        lines = [l.strip() for l in edit_hist.splitlines() if l.strip() and not l.startswith("<!--")]
                        meta["last_edit"] = lines[-1].lstrip("- ").strip() if lines else ""
                    else:
                        meta["last_edit"] = ""
                    refs.append(meta)
        except Exception:
            pass
    return refs


def call_ollama(model_str: str, prompt: str, unload_after: bool = True) -> str:
    import urllib.request as _ur
    payload = json.dumps({
        "model":      model_str,
        "prompt":     prompt,
        "stream":     False,
        # keep_alive=0 — unloads model from RAM immediately after response.
        # This is intentional: allows sequential local model firing without
        # memory pressure on the Mini. Cold start cost (~15-20s from Vault,
        # ~8-17s from internal NVMe) is accepted in exchange for not holding
        # multiple 5-10GB models in RAM simultaneously.
        "keep_alive": 0 if unload_after else "5m"
    }).encode()
    req = _ur.Request(f"{OLLAMA_BASE}/api/generate", data=payload, headers={"Content-Type": "application/json"})
    with _ur.urlopen(req, timeout=300) as r:
        return json.loads(r.read()).get("response", "")


def run_synthesis(prompt: str, responses: dict, synthesis_model: str = "deepseek", synth_mode: str = "survey") -> str:
    settings  = load_settings()
    local_cfg = settings.get("models", {}).get("local", {})
    model_map = {
        "deepseek": local_cfg.get("reasoning",  "deepseek-r1:8b"),
        "qwen":     local_cfg.get("asia",       "qwen2.5:14b"),
        "mistral":  local_cfg.get("europe",     "mistral:7b"),
        "gemma":    local_cfg.get("multimodal", "gemma4:latest"),
        "llama":    local_cfg.get("general",    "llama3.1:8b"),
        "cohere":   local_cfg.get("canadian",   "command-r7b:latest"),
    }
    model_str = model_map.get(synthesis_model, local_cfg.get("reasoning", "deepseek-r1:8b"))
    response_block = "\n\n".join(
        f"[{model.upper()}]\n{text}" for model, text in responses.items() if text
    )
    # The synthesis prompt uses ## HEADER delimiters explicitly because:
    # - Local models (DeepSeek, Qwen) sometimes ignore numbered list instructions
    #   but reliably follow markdown header formatting
    # - The frontend renderSynthesisSections() splits on /\n##\s+/ to produce
    #   colour-coded section cards — the delimiter IS the rendering instruction
    # - If a model ignores the format, the frontend falls back to plain text gracefully
    if synth_mode == "pressure":
        synth_prompt = f"""You are a research pressure-tester. A researcher brought a half-formed idea and sent it through multiple AI models. Your job is not to summarize what the models said — it is to assess what happened to the idea.

RESEARCHER'S PROMPT:
{prompt}

MODEL RESPONSES:
{response_block}

Produce exactly three sections using these exact headers (the ## prefix is required):

## SURVIVED
What held up under scrutiny across multiple responses? What did the models reinforce or leave standing?

## DESTABILIZED
What got contradicted, complicated, or weakened? Name which model challenged what.

## STILL OPEN
What remains genuinely unresolved — not answered, not refuted, just unfinished? What did none of the models reach?

Be direct. The researcher wants to know the shape of the idea after pressure, not a summary of what was said."""
    else:
        synth_prompt = f"""You are a research synthesis engine. A researcher asked the following question and received responses from multiple AI models. Synthesize these into a single analytical summary.

RESEARCHER'S QUESTION:
{prompt}

MODEL RESPONSES:
{response_block}

Produce exactly four sections using these exact headers (the ## prefix is required):

## CONSENSUS
What do the models agree on?

## DIVERGENCE
Where do they differ, and why? Name which model said what.

## UNIQUE CONTRIBUTIONS
What does each model add that others missed? Name each model.

## ABSENT VOICES
What important angles did none of the models address?

Be concise. The researcher will use this to decide what to investigate further."""
    try:
        return call_ollama(model_str, synth_prompt)
    except Exception as e:
        return f"Synthesis unavailable — DeepSeek R1 error: {e}"


# ─── Import parsers ───────────────────────────────────────────────────────────

def parse_csv_import(text: str) -> list:
    records = []
    reader = csv.DictReader(io.StringIO(text))
    field_map = {
        "title": ["title"], "authors": ["authors", "author"],
        "year": ["year"], "source_type": ["source_type", "type", "sourcetype"],
        "url_doi": ["url_doi", "doi", "url"],
        "verification_status": ["verification_status", "status"],
        "physical_holding": ["physical_holding", "holding"],
        "holding_location": ["holding_location", "location"],
        "annotation": ["annotation", "notes", "abstract"],
        "argument_connection": ["argument_connection", "argument"],
        "tags": ["tags", "keywords"],
        "themes": ["themes", "subject"],
        "connections": ["connections", "projects"],
    }
    for row in reader:
        if not any(row.values()):
            continue
        norm = {k.lower().strip(): v for k, v in row.items()}
        rec = {}
        for canonical_key, aliases in field_map.items():
            for alias in aliases:
                if alias in norm and norm[alias].strip():
                    rec[canonical_key] = norm[alias].strip()
                    break
        if rec.get("title"):
            records.append(rec)
    return records


def parse_bibtex_import(text: str) -> list:
    try:
        import bibtexparser
        db = bibtexparser.loads(text)
    except ImportError:
        return _parse_bibtex_minimal(text)
    type_map = {
        "article": "journal", "book": "book", "inbook": "chapter",
        "incollection": "chapter", "inproceedings": "conference",
        "proceedings": "conference", "phdthesis": "thesis",
        "mastersthesis": "thesis", "misc": "other", "techreport": "other",
    }
    records = []
    for entry in db.entries:
        authors_raw = entry.get("author", "")
        authors = "; ".join(a.strip() for a in authors_raw.split(" and ")) if authors_raw else ""
        rec = {
            "title":       entry.get("title", "").replace("{", "").replace("}", ""),
            "authors":     authors,
            "year":        entry.get("year", ""),
            "source_type": type_map.get(entry.get("ENTRYTYPE", "").lower(), "other"),
            "url_doi":     entry.get("doi", "") or entry.get("url", ""),
            "annotation":  entry.get("abstract", ""),
            "themes":      entry.get("keywords", ""),
        }
        if rec["title"]:
            records.append(rec)
    return records


def _parse_bibtex_minimal(text: str) -> list:
    import re
    records = []
    entries = re.findall(r'@\w+\{[^@]+\}', text, re.DOTALL)
    for entry in entries:
        def field(name):
            m = re.search(rf'{name}\s*=\s*[{{"](.+?)[{{}}"]\s*[,}}]', entry, re.IGNORECASE | re.DOTALL)
            return m.group(1).strip().replace('\n', ' ') if m else ""
        authors_raw = field("author")
        authors = "; ".join(a.strip() for a in authors_raw.split(" and ")) if authors_raw else ""
        rec = {"title": field("title").replace("{","").replace("}",""), "authors": authors, "year": field("year"), "url_doi": field("doi") or field("url")}
        if rec["title"]:
            records.append(rec)
    return records


def parse_ris_import(text: str) -> list:
    type_map = {"JOUR": "journal", "BOOK": "book", "CHAP": "chapter", "CONF": "conference", "THES": "thesis", "RPRT": "other", "ELEC": "web", "GEN": "other"}
    records, current, authors = [], {}, []
    for line in text.splitlines():
        line = line.strip()
        if not line:
            continue
        if line == "ER  -":
            if current.get("title"):
                current["authors"] = "; ".join(authors)
                records.append(current)
            current, authors = {}, []
            continue
        if len(line) < 6 or line[2:6] != "  - ":
            continue
        tag, val = line[:2].strip(), line[6:].strip()
        if tag == "TY":   current["source_type"] = type_map.get(val, "other")
        elif tag in ("TI","T1"): current["title"] = val
        elif tag in ("AU","A1","A2"): authors.append(val)
        elif tag in ("PY","Y1"): current["year"] = val[:4]
        elif tag == "DO": current["url_doi"] = val
        elif tag == "UR": current.setdefault("url_doi", val)
        elif tag == "AB": current["annotation"] = val
        elif tag == "KW": current["themes"] = (current.get("themes","") + ", " + val).strip(", ")
        elif tag == "N1": current["argument_connection"] = val
    return records


def lookup_doi(doi: str) -> dict:
    import urllib.request as _ur
    doi = doi.strip().lstrip("https://doi.org/").lstrip("http://doi.org/").lstrip("doi:")
    url = f"https://api.crossref.org/works/{doi}"
    try:
        req = _ur.Request(url, headers={"User-Agent": "Marginalia/0.9.2.5 (mailto:research@marginalia.local)"})
        with _ur.urlopen(req, timeout=10) as r:
            data = json.loads(r.read())
        msg = data.get("message", {})
        authors_list = msg.get("author", [])
        authors = "; ".join(f"{a.get('family','')}, {a.get('given','')}".strip(", ") for a in authors_list)
        year = ""
        date_parts = msg.get("published", msg.get("published-print", msg.get("published-online", {})))
        if date_parts and date_parts.get("date-parts"):
            year = str(date_parts["date-parts"][0][0])
        type_map = {"journal-article": "journal", "book": "book", "book-chapter": "chapter", "proceedings-article": "conference", "dissertation": "thesis"}
        titles = msg.get("title", [""])
        return {"title": titles[0] if titles else "", "authors": authors, "year": year, "source_type": type_map.get(msg.get("type",""), "other"), "url_doi": doi, "annotation": msg.get("abstract", "")}
    except Exception as e:
        return {"_error": str(e), "url_doi": doi}


# ─── API routes ───────────────────────────────────────────────────────────────



@app.route("/")
def index():
    from flask import make_response
    resp = make_response(render_template("index.html", app_version=APP_VERSION))
    resp.headers["Cache-Control"] = "no-store, no-cache, must-revalidate, max-age=0"
    resp.headers["Pragma"] = "no-cache"
    resp.headers["Expires"] = "0"
    return resp

@app.route("/api/settings", methods=["GET"])
def get_settings():
    return jsonify(load_settings())

@app.route("/api/settings", methods=["POST"])
def post_settings():
    save_settings(request.json)
    return jsonify({"status": "saved"})

@app.route("/api/references", methods=["GET"])
def get_references():
    return jsonify(read_all_references())

@app.route("/api/references", methods=["POST"])
def add_reference():
    filepath = write_canonical_reference(request.json)
    return jsonify({"status": "saved", "file": filepath.name})

@app.route("/api/token-usage", methods=["GET"])
def get_token_usage():
    cost = estimate_anthropic_cost(anthropic_tokens["input"], anthropic_tokens["output"])
    return jsonify({"input": anthropic_tokens["input"], "output": anthropic_tokens["output"], "cost_usd": round(cost, 4)})


@app.route("/api/import", methods=["POST"])
def import_references():
    records, parse_errors, fmt = [], [], None
    if request.files:
        file = request.files.get("file")
        if not file:
            return jsonify({"error": "No file received"}), 400
        filename = file.filename.lower()
        text = file.read().decode("utf-8", errors="replace")
        if filename.endswith(".csv"):    fmt, records = "csv",     parse_csv_import(text)
        elif filename.endswith(".bib"):  fmt, records = "bibtex",  parse_bibtex_import(text)
        elif filename.endswith(".ris"):  fmt, records = "ris",     parse_ris_import(text)
        else: return jsonify({"error": f"Unsupported file type: {filename}"}), 400
    elif request.is_json:
        body = request.json
        fmt  = body.get("format", "").lower()
        text = body.get("text", "")
        if fmt == "doi":
            dois = [d.strip() for d in text.replace(",", "\n").splitlines() if d.strip()]
            for doi in dois:
                result = lookup_doi(doi)
                if "_error" in result: parse_errors.append(f"{doi}: {result['_error']}")
                else: records.append(result)
        elif fmt == "csv":     records = parse_csv_import(text)
        elif fmt == "bibtex":  records = parse_bibtex_import(text)
        elif fmt == "ris":     records = parse_ris_import(text)
        elif fmt == "plaintext":
            settings  = load_settings()
            model_str = settings.get("models", {}).get("local", {}).get("reasoning", "deepseek-r1:8b")
            parse_prompt = f"""Parse the following reference list into JSON. Return ONLY a JSON array, no other text.
Each object must have: title, authors, year, source_type, url_doi, themes
authors = semicolon-separated. source_type = journal|book|chapter|conference|thesis|web|other

REFERENCE LIST:
{text}"""
            try:
                raw = call_ollama(model_str, parse_prompt).strip()
                if raw.startswith("```"): raw = "\n".join(raw.split("\n")[1:])
                if raw.endswith("```"):   raw = "\n".join(raw.split("\n")[:-1])
                records = json.loads(raw.strip())
            except Exception as e:
                parse_errors.append(f"Local model parse failed: {e}")
        else:
            return jsonify({"error": f"Unknown format: {fmt}"}), 400
    else:
        return jsonify({"error": "No file or JSON body received"}), 400

    imported, skipped = [], []
    for rec in records:
        if not rec.get("title"): skipped.append(rec); continue
        try:
            rec.setdefault("verification_status", "surfaced")
            rec.setdefault("physical_holding", "none")
            imported.append(write_canonical_reference(rec).name)
        except Exception as e:
            parse_errors.append(str(e))

    if imported:
        log_path = SESSIONS_DIR / "imports.md"
        timestamp = datetime.now(datetime.UTC).strftime("%Y-%m-%d %H:%M UTC")
        log_entry = f"\n### {timestamp} — {fmt} import\n"
        log_entry += f"- Imported: {len(imported)}\n"
        if skipped:  log_entry += f"- Skipped (no title): {len(skipped)}\n"
        if parse_errors: log_entry += f"- Errors: {len(parse_errors)}\n"
        for f_name in imported[:10]:
            log_entry += f"  - {f_name}\n"
        if len(imported) > 10:
            log_entry += f"  - ... and {len(imported)-10} more\n"
        try:
            if log_path.exists():
                existing = log_path.read_text(encoding="utf-8")
                log_path.write_text(existing.rstrip() + "\n" + log_entry, encoding="utf-8")
            else:
                log_path.write_text(f"# Import Log\n{log_entry}", encoding="utf-8")
        except Exception:
            pass

    return jsonify({"format": fmt, "imported": len(imported), "skipped": len(skipped), "errors": parse_errors, "files": imported})


@app.route("/api/doi-lookup", methods=["POST"])
def doi_lookup():
    doi = request.json.get("doi", "")
    if not doi: return jsonify({"error": "No DOI provided"}), 400
    return jsonify(lookup_doi(doi))


@app.route("/api/setup-status", methods=["GET"])
def setup_status():
    has_any_cloud_key = any([
        bool(KEYS.get("gemini")),
        bool(KEYS.get("anthropic")),
        bool(KEYS.get("openai")),
    ])
    ollama_models_path = os.getenv("OLLAMA_MODELS_PATH", "")
    setup_file = "setup.env" if (APP_ROOT / "setup.env").exists() else ".env"
    return jsonify({
        "configured":        has_any_cloud_key,
        "has_gemini":        bool(KEYS.get("gemini")),
        "has_anthropic":     bool(KEYS.get("anthropic")),
        "has_openai":        bool(KEYS.get("openai")),
        "has_ollama_path":   bool(ollama_models_path),
        "ollama_models_path": ollama_models_path,
        "setup_file":        setup_file,
        "setup_file_path":   str(APP_ROOT / setup_file),
    })


@app.route("/api/local-models", methods=["GET"])
def get_local_models():
    import urllib.request as _ur
    LOCAL_MODEL_MAP = {
        "deepseek": ["deepseek-r1"],
        "qwen":     ["qwen2.5", "qwen"],
        "mistral":  ["mistral"],
        "gemma":    ["gemma4", "gemma"],
        "llama":    ["llama3.1", "llama3", "llama"],
        "cohere":   ["command-r7b", "command-r"],
    }
    installed = {}
    try:
        req = _ur.Request(f"{OLLAMA_BASE}/api/tags", headers={"Content-Type": "application/json"})
        with _ur.urlopen(req, timeout=5) as r:
            data = json.loads(r.read())
        ollama_models = {m["name"]: m for m in data.get("models", [])}
        claimed_ollama_names = set()
        for chip_key, prefixes in LOCAL_MODEL_MAP.items():
            found = None
            for name, info in ollama_models.items():
                for prefix in prefixes:
                    if name.startswith(prefix):
                        found = {"installed": True, "model_str": name, "size_gb": round(info.get("size", 0) / 1e9, 1)}
                        claimed_ollama_names.add(name)
                        break
                if found:
                    break
            installed[chip_key] = found or {"installed": False, "model_str": None, "size_gb": 0}
        for name, info in ollama_models.items():
            if name not in claimed_ollama_names:
                chip_key = "ollama:" + name
                installed[chip_key] = {"installed": True, "model_str": name, "size_gb": round(info.get("size", 0) / 1e9, 1), "dynamic": True}
    except Exception as e:
        for chip_key in LOCAL_MODEL_MAP:
            installed[chip_key] = {"installed": None, "model_str": None, "size_gb": 0, "error": str(e)}
    return jsonify(installed)


@app.route("/api/key-status", methods=["GET"])
def key_status():
    return jsonify({
        "gemini":    bool(KEYS.get("gemini")),
        "anthropic": bool(KEYS.get("anthropic")),
        "openai":    bool(KEYS.get("openai")),
        "deepseek":  True,
        "gemma":     True,
        "llama":     True,
        "qwen":      True,
        "mistral":   True,
        "cohere":    True,
    })


def call_model(model, prompt):
    settings  = load_settings()
    local_cfg = settings.get("models", {}).get("local", {})
    try:
        if model == "gemini" and KEYS.get("gemini"):
            import google.generativeai as genai
            genai.configure(api_key=KEYS["gemini"])
            r = genai.GenerativeModel("gemini-2.5-flash").generate_content(prompt, request_options={"timeout": 30})
            return (model, r.text, None, 0, 0)
        elif model == "anthropic" and KEYS.get("anthropic"):
            import anthropic as _anth
            client = _anth.Anthropic(api_key=KEYS["anthropic"])
            msg = client.messages.create(model="claude-haiku-4-5", max_tokens=1024,
                                         messages=[{"role": "user", "content": prompt}])
            return (model, msg.content[0].text, None, msg.usage.input_tokens, msg.usage.output_tokens)
        elif model == "openai" and KEYS.get("openai"):
            from openai import OpenAI
            client = OpenAI(api_key=KEYS["openai"])
            r = client.chat.completions.create(model="gpt-4o", messages=[{"role": "user", "content": prompt}])
            return (model, r.choices[0].message.content, None, 0, 0)
        elif model == "deepseek":
            return (model, call_ollama(local_cfg.get("reasoning",  "deepseek-r1:8b"),    prompt), None, 0, 0)
        elif model == "gemma":
            return (model, call_ollama(local_cfg.get("multimodal", "gemma4:latest"),     prompt), None, 0, 0)
        elif model == "llama":
            return (model, call_ollama(local_cfg.get("general",    "llama3.1:8b"),       prompt), None, 0, 0)
        elif model == "qwen":
            return (model, call_ollama(local_cfg.get("asia",       "qwen2.5:14b"),       prompt), None, 0, 0)
        elif model == "mistral":
            return (model, call_ollama(local_cfg.get("europe",     "mistral:7b"),        prompt), None, 0, 0)
        elif model == "cohere":
            return (model, call_ollama(local_cfg.get("canadian",   "command-r7b:latest"),       prompt), None, 0, 0)
        elif model.startswith("ollama:"):
            return (model, call_ollama(model[len("ollama:"):], prompt), None, 0, 0)
        else:
            return (model, None, "No key configured", 0, 0)
    except Exception as e:
        return (model, None, str(e), 0, 0)


MODEL_ORDER  = ["gemini", "anthropic", "openai", "deepseek", "qwen", "mistral", "cohere", "gemma", "llama"]
CLOUD_MODELS = {"gemini", "anthropic", "openai"}
LOCAL_MODELS = {"deepseek", "gemma", "llama", "qwen", "mistral", "cohere"}


@app.route("/api/prompt", methods=["POST"])
def handle_prompt():
    global anthropic_tokens
    data            = request.json
    tab_id          = data.get("tab_id", "")
    lock_err        = _require_lock(tab_id)
    if lock_err:
        return lock_err
    prompt          = data.get("prompt", "")
    models          = data.get("models", [])
    synthesis_model = data.get("synthesis_model", "deepseek")
    synth_mode      = data.get("synth_mode", "survey")

    dynamic_local = [m for m in models if m.startswith("ollama:")]
    cloud_ordered = [m for m in MODEL_ORDER if m in models and m in CLOUD_MODELS]
    local_ordered = [m for m in MODEL_ORDER if m in models and m in LOCAL_MODELS] + dynamic_local

    def generate():
        import concurrent.futures
        results, errors = {}, {}

        if cloud_ordered:
            for m in cloud_ordered:
                yield json.dumps({"event": "start", "model": m}) + "\n"
            with concurrent.futures.ThreadPoolExecutor() as ex:
                futures = {ex.submit(call_model, m, prompt): m for m in cloud_ordered}
                for future in concurrent.futures.as_completed(futures):
                    model, result, error, in_tok, out_tok = future.result()
                    if in_tok:
                        with _tokens_lock:
                            anthropic_tokens["input"]  += in_tok
                            anthropic_tokens["output"] += out_tok
                    if result:
                        results[model] = result
                        yield json.dumps({"event": "result", "model": model, "text": result}) + "\n"
                    else:
                        errors[model] = error or "No response"
                        yield json.dumps({"event": "error", "model": model, "error": errors[model]}) + "\n"

        for model in local_ordered:
            yield json.dumps({"event": "start", "model": model}) + "\n"
            import time; time.sleep(0.05)
            yield json.dumps({"event": "heartbeat"}) + "\n"
            _, result, error, _, _ = call_model(model, prompt)
            if result:
                results[model] = result
                yield json.dumps({"event": "result", "model": model, "text": result}) + "\n"
            else:
                errors[model] = error or "No response"
                yield json.dumps({"event": "error", "model": model, "error": errors[model]}) + "\n"

        synthesis = ""
        if len(results) > 1:
            yield json.dumps({"event": "synthesis_start"}) + "\n"
            synthesis = run_synthesis(prompt, results, synthesis_model=synthesis_model, synth_mode=synth_mode)
            yield json.dumps({"event": "synthesis", "text": synthesis}) + "\n"

        if results:
            # Save full prompt including separator layers for canonical record
            full_prompt = data.get("full_prompt", prompt)
            project_tag = data.get("project", "")
            writing_tag = data.get("writing", "")
            write_canonical_session(full_prompt, results, synthesis, project=project_tag, writing=writing_tag)

        cost = estimate_anthropic_cost(anthropic_tokens["input"], anthropic_tokens["output"])
        yield json.dumps({
            "event":              "done",
            "session_saved":      bool(results),
            "anthropic_cost_usd": round(cost, 4),
        }) + "\n"

    return Response(
        stream_with_context(generate()),
        mimetype="text/event-stream",
        headers={"X-Accel-Buffering": "no", "Cache-Control": "no-cache"}
    )


@app.route("/api/references/<ref_filename>", methods=["PUT"])
def update_reference(ref_filename):
    if "/" in ref_filename or "\\" in ref_filename or ".." in ref_filename:
        return jsonify({"error": "Invalid filename"}), 400
    filepath = (REFERENCES_DIR / ref_filename).resolve()
    if REFERENCES_DIR.resolve() not in filepath.parents:
        return jsonify({"error": "Invalid path"}), 400
    if not filepath.exists():
        return jsonify({"error": "Reference not found"}), 404

    data = request.json or {}
    text = filepath.read_text(encoding="utf-8")
    parts = text.split("---", 2)
    if len(parts) < 3:
        return jsonify({"error": "Invalid canonical format"}), 400

    meta = {}
    for line in parts[1].strip().splitlines():
        if ": " in line:
            k, v = line.split(": ", 1)
            meta[k.strip()] = v.strip()

    for field in ["title","authors","year","source_type","url_doi","themes",
                  "annotation","argument_connection","verification_status",
                  "physical_holding","holding_location"]:
        if field in data:
            meta[field] = str(data[field]).strip()

    body = parts[2]
    def replace_section(body, heading, new_content):
        if not new_content:
            return body
        marker = "## " + heading
        if marker in body:
            before = body.split(marker)[0]
            rest   = body.split(marker)[1]
            after  = ("\n## " + rest.split("\n## ", 1)[1]) if "\n## " in rest else ""
            return before + marker + "\n" + new_content + "\n" + after
        else:
            return body.rstrip() + "\n\n" + marker + "\n" + new_content + "\n"

    def ensure_sections(body):
        for section in ["Themes", "Connections", "Annotation", "Argument Connection", "Your Annotation", "Edit History", "Status History"]:
            if "## " + section not in body:
                placeholder = {
                    "Themes": "<!-- Conceptual themes — full phrases, one per line as: - theme -->",
                    "Connections": "<!-- Connections to writing/projects: name | note -->",
                    "Annotation": "<!-- AI annotation — run Generate to populate -->",
                    "Argument Connection": "<!-- How does this source support, complicate, or challenge your research argument? -->",
                    "Your Annotation": "<!-- Your own critical reading of this source -->",
                }.get(section, "")
                if placeholder:
                    body = body.rstrip() + "\n\n## " + section + "\n" + placeholder + "\n"
        return body

    body = ensure_sections(body)
    if "annotation" in data and data["annotation"]:
        body = replace_section(body, "Annotation", data["annotation"])
        meta.pop("annotation", None)
    if "argument_connection" in data and data["argument_connection"]:
        body = replace_section(body, "Argument Connection", data["argument_connection"])
        meta.pop("argument_connection", None)
    if "user_notes" in data and data["user_notes"]:
        body = replace_section(body, "Your Annotation", data["user_notes"])
        meta.pop("user_notes", None)
    if "themes_body" in data and data["themes_body"]:
        body = replace_section(body, "Themes", data["themes_body"])
        meta.pop("themes", None)
    if "connections" in data:
        body = replace_section(body, "Connections", data["connections"])
    if "tags" in data:
        meta["tags"] = data["tags"]

    meta["updated_at"] = datetime.now(datetime.UTC).isoformat()

    tracked = ["title","authors","year","source_type","url_doi","tags","physical_holding","holding_location","verification_status"]
    changed = [f for f in tracked if f in data and str(data[f]).strip() != str(meta.get(f,"")).strip()]
    body_changed = [s for s in ["annotation","themes_body","connections","argument_connection","user_notes"] if s in data and data[s]]
    all_changed = changed + body_changed
    if all_changed:
        timestamp = datetime.now(datetime.UTC).strftime("%Y-%m-%d %H:%M UTC")
        edit_line = f"- [{timestamp}] edited: {', '.join(all_changed)}"
        log_marker = "## Edit History"
        if log_marker in body:
            body = body.rstrip() + "\n" + edit_line + "\n"
        else:
            body = body.rstrip() + "\n\n" + log_marker + "\n" + edit_line + "\n"

    fm_lines = "\n".join(f"{k}: {v}" for k, v in meta.items() if v)
    new_file = f"---\n{fm_lines}\n---\n{body}"
    filepath.write_text(new_file, encoding="utf-8")
    return jsonify({"status": "updated", "filename": ref_filename})


@app.route("/api/references/<ref_filename>", methods=["DELETE"])
def delete_reference(ref_filename):
    if "/" in ref_filename or "\\" in ref_filename or ".." in ref_filename:
        return jsonify({"error": "Invalid filename"}), 400
    filepath = (REFERENCES_DIR / ref_filename).resolve()
    if REFERENCES_DIR.resolve() not in filepath.parents:
        return jsonify({"error": "Invalid path"}), 400
    if not filepath.exists():
        return jsonify({"error": "Reference not found"}), 404
    filepath.unlink()
    return jsonify({"status": "deleted", "filename": ref_filename})


@app.route("/api/references/<ref_filename>/status", methods=["PATCH"])
def update_reference_status(ref_filename):
    if "/" in ref_filename or "\\" in ref_filename or ".." in ref_filename:
        return jsonify({"error": "Invalid filename"}), 400
    filepath = (REFERENCES_DIR / ref_filename).resolve()
    if REFERENCES_DIR.resolve() not in filepath.parents:
        return jsonify({"error": "Invalid path"}), 400
    if not filepath.exists():
        return jsonify({"error": "Reference not found"}), 404

    new_status = (request.json or {}).get("status", "")
    valid = {"surfaced", "located", "verified"}
    if new_status not in valid:
        return jsonify({"error": f"Invalid status. Must be one of: {valid}"}), 400

    text = filepath.read_text(encoding="utf-8")
    parts = text.split("---", 2)
    if len(parts) < 3:
        return jsonify({"error": "Invalid canonical format"}), 400

    meta = {}
    for line in parts[1].strip().splitlines():
        if ": " in line:
            k, v = line.split(": ", 1)
            meta[k.strip()] = v.strip()

    old_status = meta.get("verification_status", "surfaced")
    meta["verification_status"] = new_status

    timestamp = datetime.now(datetime.UTC).strftime("%Y-%m-%d %H:%M")
    body = parts[2]
    log_marker = "## Status History"
    log_line   = f"- {old_status} → **{new_status}** [{timestamp}]"
    if log_marker in body:
        body = body.rstrip() + "\n" + log_line + "\n"
    else:
        body = body.rstrip() + "\n\n" + log_marker + "\n" + log_line + "\n"

    fm_lines = "\n".join(f"{k}: {v}" for k, v in meta.items() if v)
    filepath.write_text(f"---\n{fm_lines}\n---\n{body}", encoding="utf-8")
    return jsonify({"status": "updated", "verification_status": new_status})


# ─── Projects ─────────────────────────────────────────────────────────────────

@app.route("/api/projects", methods=["GET"])
def get_projects():
    projects = []
    all_refs = read_all_references()
    for filepath in sorted(PROJECTS_DIR.glob("*.md")):
        try:
            text = filepath.read_text(encoding="utf-8")
            if text.startswith("---"):
                parts = text.split("---", 2)
                if len(parts) >= 3:
                    meta = {}
                    for line in parts[1].strip().splitlines():
                        if ": " in line:
                            k, v = line.split(": ", 1)
                            meta[k.strip()] = v.strip()
                    meta["_filename"] = filepath.name
                    if not meta.get("slug"):
                        meta["slug"] = meta.get("name", filepath.stem)
                    if not meta.get("label"):
                        meta["label"] = meta.get("slug", filepath.stem)
                    body = parts[2]
                    if "## Framing" in body:
                        raw = body.split("## Framing")[1].split("\n## ")[0].strip()
                        meta["framing"] = raw if not raw.startswith("<!--") else ""
                    slug = meta["slug"]
                    connected = [r for r in all_refs
                                 if any(slug in line.split("|")[0].strip()
                                        for line in (r.get("conn_list") or []))]
                    meta["ref_count"] = len(connected)
                    meta["ref_titles"] = [r.get("title","")[:60] for r in connected[:5]]
                    projects.append(meta)
        except Exception:
            pass
    return jsonify(projects)


@app.route("/api/projects/<project_slug>", methods=["PUT"])
def update_project(project_slug):
    safe = project_slug.replace("/","").replace("..","")
    filepath = PROJECTS_DIR / (safe + ".md")
    if not filepath.exists():
        return jsonify({"error": "Not found"}), 404
    data  = request.json or {}
    text  = filepath.read_text(encoding="utf-8")
    parts = text.split("---", 2)
    if len(parts) < 3:
        return jsonify({"error": "Invalid format"}), 400
    meta = {}
    for line in parts[1].strip().splitlines():
        if ": " in line:
            k, v = line.split(": ", 1)
            meta[k.strip()] = v.strip()
    for field in ["label", "status"]:
        if field in data:
            meta[field] = data[field]
    new_slug = data.get("slug", "").strip().lower().replace(" ", "-")
    if new_slug and new_slug != safe:
        meta["slug"] = new_slug
        new_filepath = PROJECTS_DIR / (new_slug + ".md")
    else:
        new_filepath = filepath
    meta["updated_at"] = datetime.now(datetime.UTC).isoformat()
    body = parts[2]
    if "framing" in data and data["framing"]:
        if "## Framing" in body:
            before = body.split("## Framing")[0]
            rest   = body.split("## Framing")[1]
            after  = ("\n## " + rest.split("\n## ",1)[1]) if "\n## " in rest else ""
            body   = before + "## Framing\n" + data["framing"] + "\n" + after
        else:
            body = body.rstrip() + "\n\n## Framing\n" + data["framing"] + "\n"
    fm_lines = "\n".join(f"{k}: {v}" for k, v in meta.items() if v)
    new_filepath.write_text(f"---\n{fm_lines}\n---\n{body}", encoding="utf-8")
    if new_filepath != filepath:
        filepath.unlink()
    return jsonify({"status": "updated", "slug": new_slug or safe})


@app.route("/api/projects", methods=["POST"])
def create_project():
    data = request.json or {}
    label = data.get("label", "").strip()
    slug  = data.get("slug", "").strip().lower().replace(" ", "-") or \
            "-".join(label.lower().split()[:4])
    if not slug:
        return jsonify({"error": "Project slug required"}), 400
    filename = slug + ".md"
    filepath = PROJECTS_DIR / filename
    framing  = data.get("framing", "")
    canonical = f"""---
label: {label or slug}
slug: {slug}
status: active
created_at: {datetime.now(datetime.UTC).isoformat()}
updated_at: {datetime.now(datetime.UTC).isoformat()}
---

## Framing
{framing or "<!-- Research question or framing for this project -->"}

## Sessions

## Syntheses

"""
    filepath.write_text(canonical, encoding="utf-8")
    return jsonify({"status": "created", "filename": filename, "slug": slug, "label": label or slug})


@app.route("/api/projects/<project_name>", methods=["GET"])
def get_project(project_name):
    filepath = PROJECTS_DIR / (project_name.replace("/","").replace("..","") + ".md")
    if not filepath.exists():
        return jsonify({"error": "Not found"}), 404
    refs = [r for r in read_all_references()
            if any(project_name in line.split("|")[0].strip()
                   for line in (r.get("conn_list") or []))]
    return jsonify({"ref_count": len(refs), "refs": [r.get("title","") for r in refs]})


# ─── Writing ──────────────────────────────────────────────────────────────────

@app.route("/api/writing", methods=["GET"])
def get_writing():
    items = []
    for filepath in sorted(WRITING_DIR.glob("*.md")):
        try:
            text = filepath.read_text(encoding="utf-8")
            if text.startswith("---"):
                parts = text.split("---", 2)
                if len(parts) >= 3:
                    meta = {}
                    for line in parts[1].strip().splitlines():
                        if ": " in line:
                            k, v = line.split(": ", 1)
                            meta[k.strip()] = v.strip()
                    meta["_filename"] = filepath.name
                    items.append(meta)
        except Exception:
            pass
    return jsonify(items)


@app.route("/api/writing/<writing_slug>", methods=["PUT"])
def update_writing(writing_slug):
    safe = writing_slug.replace("/","").replace("..","")
    filepath = WRITING_DIR / (safe + ".md")
    if not filepath.exists():
        return jsonify({"error": "Not found"}), 404
    data  = request.json or {}
    text  = filepath.read_text(encoding="utf-8")
    parts = text.split("---", 2)
    if len(parts) < 3:
        return jsonify({"error": "Invalid format"}), 400
    meta = {}
    for line in parts[1].strip().splitlines():
        if ": " in line:
            k, v = line.split(": ", 1)
            meta[k.strip()] = v.strip()
    for field in ["title", "type", "project", "status"]:
        if field in data:
            meta[field] = data[field]
    new_slug = data.get("slug", "").strip().lower().replace(" ", "-")
    if new_slug and new_slug != safe:
        meta["slug"] = new_slug
        new_filepath = WRITING_DIR / (new_slug + ".md")
    else:
        new_filepath = filepath
    meta["updated_at"] = datetime.now(datetime.UTC).isoformat()
    fm_lines = "\n".join(f"{k}: {v}" for k, v in meta.items() if v)
    new_filepath.write_text(f"---\n{fm_lines}\n---\n{parts[2]}", encoding="utf-8")
    if new_filepath != filepath:
        filepath.unlink()
    return jsonify({"status": "updated", "slug": new_slug or safe})


@app.route("/api/writing", methods=["POST"])
def create_writing():
    data = request.json or {}
    title = data.get("title", "").strip()
    slug  = data.get("slug", "").strip().lower().replace(" ", "-") or \
            "-".join(title.lower().split()[:4])
    if not title:
        return jsonify({"error": "Title required"}), 400
    filename = slug + ".md"
    filepath = WRITING_DIR / filename
    canonical = f"""---
title: {title}
slug: {slug}
type: {data.get("type", "other")}
project: {data.get("project", "")}
status: drafting
created_at: {datetime.now(datetime.UTC).isoformat()}
updated_at: {datetime.now(datetime.UTC).isoformat()}
---

## Argument

## Connected References

## Notes

"""
    filepath.write_text(canonical, encoding="utf-8")
    return jsonify({"status": "created", "filename": filename, "slug": slug})


@app.route("/api/projects/<project_name>/synthesis", methods=["POST"])
def save_project_synthesis(project_name):
    safe = project_name.replace("/","").replace("..","")
    filepath = PROJECTS_DIR / (safe + ".md")
    if not filepath.exists():
        return jsonify({"error": "Project not found"}), 404
    synthesis = (request.json or {}).get("synthesis", "")
    if not synthesis:
        return jsonify({"error": "No synthesis provided"}), 400
    timestamp = datetime.now(datetime.UTC).strftime("%Y-%m-%d %H:%M UTC")
    entry = f"\n### Library synthesis — {timestamp}\n\n{synthesis}\n"
    text  = filepath.read_text(encoding="utf-8")
    parts = text.split("---", 2)
    if len(parts) >= 3:
        body = parts[2]
        if "## Syntheses" in body:
            body = body.replace("## Syntheses", "## Syntheses" + entry, 1)
        else:
            body = body.rstrip() + "\n\n## Syntheses" + entry
        meta_block = parts[1]
        import re
        meta_block = re.sub(r'updated_at:.*', f'updated_at: {datetime.now(datetime.UTC).isoformat()}', meta_block)
        filepath.write_text(f"---{meta_block}---\n{body}", encoding="utf-8")
    return jsonify({"status": "saved"})


@app.route("/api/tags", methods=["GET"])
def get_all_tags():
    tags = set()
    for ref in read_all_references():
        for t in ref.get("tags_list", []):
            if t:
                tags.add(t.lower().strip())
    return jsonify(sorted(tags))


@app.route("/api/connections", methods=["GET"])
def get_all_connections():
    conns = set()
    for ref in read_all_references():
        for line in ref.get("conn_list", []):
            name = line.split("|")[0].strip()
            if name:
                conns.add(name.lower().strip())
    return jsonify(sorted(conns))


@app.route("/api/references/library-synthesis", methods=["POST"])
def library_synthesis():
    data    = request.json or {}
    project = data.get("project", "").strip()
    req_model = data.get("model", "").strip()

    all_refs = read_all_references()
    if not all_refs:
        return jsonify({"error": "No references found in library"}), 400

    # Filter by project slug when set — match against conn_list
    if project:
        refs = [r for r in all_refs
                if any(project in line.split("|")[0].strip()
                       for line in (r.get("conn_list") or []))]
        if not refs:
            return jsonify({"error": f"No references connected to project '{project}'"}), 400
    else:
        refs = all_refs

    ref_summaries = []
    for ref in refs:
        if ref.get("title"):
            entry = f"[{ref.get('authors','Unknown')} {ref.get('year','')}] {ref.get('title','')}"
            if ref.get("themes"):
                entry += f" — themes: {ref.get('themes')}"
            filepath = REFERENCES_DIR / ref.get("_filename", "")
            if filepath.exists():
                text = filepath.read_text(encoding="utf-8")
                parts = text.split("---", 2)
                if len(parts) >= 3:
                    body = parts[2].strip()
                    if "## Annotation" in body:
                        ann = body.split("## Annotation")[1].split("##")[0].strip()
                        if ann and not ann.startswith("<!--"):
                            entry += f"\nAnnotation: {ann[:200]}"
            ref_summaries.append(entry)

    library_text = "\n\n".join(ref_summaries)
    settings  = load_settings()
    local_cfg = settings.get("models", {}).get("local", {})
    _model_map = {
        "deepseek": local_cfg.get("reasoning",  "deepseek-r1:8b"),
        "qwen":     local_cfg.get("asia",       "qwen2.5:14b"),
        "mistral":  local_cfg.get("europe",     "mistral:7b"),
        "cohere":   local_cfg.get("canadian",   "command-r7b:latest"),
        "gemma":    local_cfg.get("multimodal", "gemma4:latest"),
        "llama":    local_cfg.get("general",    "llama3.1:8b"),
    }
    model_str = _model_map.get(req_model, local_cfg.get("reasoning", "deepseek-r1:8b"))

    # Load project framing if scoped — inject so the model knows the research lens
    framing = ""
    if project:
        proj_file = PROJECTS_DIR / (project + ".md")
        if proj_file.exists():
            try:
                pt  = proj_file.read_text(encoding="utf-8")
                pp  = pt.split("---", 2)
                if len(pp) >= 3 and "## Framing" in pp[2]:
                    raw = pp[2].split("## Framing")[1].split("\n## ")[0].strip()
                    if raw and not raw.startswith("<!--"):
                        framing = raw
            except Exception:
                pass

    framing_block = f"\nRESEARCH FRAMING:\n{framing}\n" if framing else ""
    scope = f"project '{project}'" if project else "full library"

    lens_prompt = f"""You are a research librarian helping a PhD researcher understand their own collection.
Read the following reference library ({scope}) and produce exactly five sections using these exact headers:

## RECURRING THEMES
What topics and concepts appear most frequently? Be specific — cite author names and years.

## TENSIONS
Which sources argue against each other, or represent competing frameworks? Cite directly.

## ABSENT VOICES
What perspectives, epistemological traditions, or communities are missing from this collection? Who is not in the room?

## CONVERSATIONS
Which sources should be read together and why? Surface unexpected connections.

## RESEARCH QUESTION FIT
How well does this collection serve the research framing? Where are the strongest supports and the weakest coverage?
{framing_block}
Use only the researcher's own curated material — do not introduce outside sources.

LIBRARY:
{library_text}"""

    try:
        synthesis = call_ollama(model_str, lens_prompt)
        return jsonify({"synthesis": synthesis, "ref_count": len(refs), "project": project})
    except Exception as e:
        return jsonify({"error": str(e)}), 500


@app.route("/api/sessions/list", methods=["GET"])
def sessions_list():
    """
    Return session metadata for the related-sessions strip.
    Optional ?project=slug filter. Returns up to 20 most recent.
    """
    project_filter = request.args.get("project", "").strip()
    sessions = []
    if SESSIONS_DIR.exists():
        for f in sorted(SESSIONS_DIR.iterdir(), key=lambda x: x.stat().st_mtime, reverse=True):
            if not f.name.endswith(".md"):
                continue
            try:
                text = f.read_text(encoding="utf-8")
                # Extract frontmatter fields
                fm = {}
                if text.startswith("---"):
                    end = text.find("---", 3)
                    if end > 0:
                        for line in text[3:end].splitlines():
                            if ":" in line:
                                k, v = line.split(":", 1)
                                fm[k.strip()] = v.strip()
                # Skip captures
                if fm.get("source_type") == "capture":
                    continue
                proj = fm.get("project", "")
                if project_filter and proj != project_filter:
                    continue
                sessions.append({
                    "filename": f.name,
                    "title":    fm.get("title") or fm.get("prompt", "")[:60] or f.stem,
                    "project":  proj,
                    "created":  fm.get("created_at", ""),
                })
                if len(sessions) >= 20:
                    break
            except Exception:
                continue
    return jsonify({"sessions": sessions})


@app.route("/api/sessions/<session_filename>", methods=["PATCH"])
def patch_session(session_filename):
    """
    Retroactive tagging — update project and/or writing fields on a saved session.
    Only these two fields are patchable: the canonical session body is never touched.
    This exists because sessions often get saved before the researcher has named
    what they were working on — the Intelligence tab session list surfaces this gap.
    """
    if "/" in session_filename or "\\" in session_filename or ".." in session_filename:
        return jsonify({"error": "Invalid filename"}), 400
    filepath = (SESSIONS_DIR / session_filename).resolve()
    if not filepath.exists():
        return jsonify({"error": "Session not found"}), 404

    data = request.json or {}
    text = filepath.read_text(encoding="utf-8")
    if not text.startswith("---"):
        return jsonify({"error": "Invalid session format"}), 400

    parts = text.split("---", 2)
    if len(parts) < 3:
        return jsonify({"error": "Invalid session format"}), 400

    meta = {}
    for line in parts[1].strip().splitlines():
        if ": " in line:
            k, v = line.split(": ", 1)
            meta[k.strip()] = v.strip()

    if "project" in data:
        meta["project"] = data["project"].strip()
    if "writing" in data:
        meta["writing"] = data["writing"].strip()

    fm_lines = "\n".join(f"{k}: {v}" for k, v in meta.items())
    filepath.write_text(f"---\n{fm_lines}\n---\n{parts[2]}", encoding="utf-8")
    return jsonify({"status": "updated", "filename": session_filename})

@app.route("/api/sessions/synthesis", methods=["POST"])
def sessions_synthesis():
    data    = request.json or {}
    project = data.get("project", "").strip()
    req_model = data.get("model", "").strip()

    session_files = sorted(SESSIONS_DIR.glob("session_*.md"), reverse=True)
    if not session_files:
        return jsonify({"error": "No sessions found"}), 400

    summaries = []
    matched   = 0
    for filepath in session_files:
        try:
            text  = filepath.read_text(encoding="utf-8")
            parts = text.split("---", 2)
            if len(parts) < 3:
                continue
            # Parse frontmatter
            meta = {}
            for line in parts[1].strip().splitlines():
                if ": " in line:
                    k, v = line.split(": ", 1)
                    meta[k.strip()] = v.strip()
            body = parts[2]

            # Filter logic: frontmatter project field first, text match fallback
            if project:
                fm_project = meta.get("project", "").strip()
                if fm_project:
                    if fm_project != project:
                        continue  # frontmatter present, doesn't match — skip
                else:
                    # Old session — fall back to text match on prompt + responses
                    if project.lower() not in body.lower():
                        continue

            # Extract prompt
            prompt_text = ""
            if "## Prompt" in body:
                prompt_text = body.split("## Prompt")[1].split("\n## ")[0].strip()[:300]

            # Extract synthesis if present
            synth_text = ""
            if "## Synthesis" in body:
                raw = body.split("## Synthesis")[1].split("\n## ")[0].strip()
                if raw and not raw.startswith("<!--"):
                    synth_text = raw[:300]

            label    = meta.get("prompt_label", "") or prompt_text[:80]
            created  = meta.get("created_at", "")[:16].replace("T", " ")
            models   = meta.get("models", "")
            entry    = f"[{created}] {label}\nModels: {models}"
            if synth_text:
                entry += f"\nSynthesis: {synth_text}"
            elif prompt_text:
                entry += f"\nPrompt: {prompt_text}"
            summaries.append(entry)
            matched += 1
            if matched >= 20:  # cap at 20 sessions to avoid context overflow
                break
        except Exception:
            continue

    if not summaries:
        return jsonify({"error": f"No sessions found{' for project ' + project if project else ''}"}), 400

    settings  = load_settings()
    local_cfg = settings.get("models", {}).get("local", {})
    _model_map = {
        "deepseek": local_cfg.get("reasoning",  "deepseek-r1:8b"),
        "qwen":     local_cfg.get("asia",       "qwen2.5:14b"),
        "mistral":  local_cfg.get("europe",     "mistral:7b"),
        "cohere":   local_cfg.get("canadian",   "command-r7b:latest"),
        "gemma":    local_cfg.get("multimodal", "gemma4:latest"),
        "llama":    local_cfg.get("general",    "llama3.1:8b"),
    }
    model_str = _model_map.get(req_model, local_cfg.get("reasoning", "deepseek-r1:8b"))

    # Load project framing if scoped
    framing = ""
    if project:
        proj_file = PROJECTS_DIR / (project + ".md")
        if proj_file.exists():
            try:
                pt  = proj_file.read_text(encoding="utf-8")
                pp  = pt.split("---", 2)
                if len(pp) >= 3 and "## Framing" in pp[2]:
                    raw = pp[2].split("## Framing")[1].split("\n## ")[0].strip()
                    if raw and not raw.startswith("<!--"):
                        framing = raw
            except Exception:
                pass

    framing_block = f"\nRESEARCH FRAMING:\n{framing}\n" if framing else ""
    scope        = f"project '{project}'" if project else "all projects"
    session_text = "\n\n---\n\n".join(summaries)

    lens_prompt = f"""You are a research assistant helping a PhD researcher understand their own thinking over time.
Read the following research session log ({scope}) and produce exactly five sections using these exact headers:

## RECURRING QUESTIONS
What questions or problems keep coming up across sessions? Reference specific dates.

## EVOLUTION
How has the thinking shifted across sessions? What changed and when?

## UNRESOLVED
What threads were raised but never followed up? What was left hanging?

## MOMENTUM
Where is the research moving? What seems to be building toward something?

## ABSENT VOICES
What important questions haven't been asked yet? What is conspicuously absent from the inquiry?
{framing_block}
Be specific — reference session dates and prompts. This is the researcher's own work.

SESSIONS:
{session_text}"""

    try:
        synthesis = call_ollama(model_str, lens_prompt)
        return jsonify({"synthesis": synthesis, "session_count": matched, "project": project})
    except Exception as e:
        return jsonify({"error": str(e)}), 500


@app.route("/api/sessions/predict", methods=["POST"])
def sessions_predict():
    """
    v0.9.3 — What am I missing?
    Predictive gap analysis: reads sessions and references for a project,
    surfaces argument weaknesses, unasked questions, missing perspectives.
    The instrument auditing its own gaps.
    """
    data      = request.json or {}
    project   = data.get("project", "").strip()
    req_model = data.get("model", "").strip()

    # Load sessions — same logic as sessions_synthesis
    session_files = sorted(SESSIONS_DIR.glob("session_*.md"), reverse=True)
    summaries = []
    matched   = 0
    for filepath in session_files:
        try:
            text  = filepath.read_text(encoding="utf-8")
            parts = text.split("---", 2)
            if len(parts) < 3:
                continue
            meta = {}
            for line in parts[1].strip().splitlines():
                if ": " in line:
                    k, v = line.split(": ", 1)
                    meta[k.strip()] = v.strip()
            body = parts[2]
            if project:
                fm_project = meta.get("project", "").strip()
                if fm_project:
                    if fm_project != project:
                        continue
                else:
                    if project.lower() not in body.lower():
                        continue
            prompt_text = ""
            if "## Prompt" in body:
                prompt_text = body.split("## Prompt")[1].split("\n## ")[0].strip()[:400]
            synth_text = ""
            if "## Synthesis" in body:
                raw = body.split("## Synthesis")[1].split("\n## ")[0].strip()
                if raw and not raw.startswith("<!--"):
                    synth_text = raw[:300]
            label   = meta.get("prompt_label", "") or prompt_text[:80]
            created = meta.get("created_at", "")[:16].replace("T", " ")
            entry   = f"[{created}] {label}"
            if synth_text:
                entry += f"\nSynthesis: {synth_text}"
            elif prompt_text:
                entry += f"\nPrompt: {prompt_text}"
            summaries.append(entry)
            matched += 1
            if matched >= 20:
                break
        except Exception:
            continue

    if not summaries:
        return jsonify({"error": f"No sessions found{' for project ' + project if project else ''}"}), 400

    # Also pull connected reference titles for context
    ref_context = ""
    if project:
        all_refs = read_all_references()
        connected = [r for r in all_refs
                     if any(project in line.split("|")[0].strip()
                            for line in (r.get("conn_list") or []))]
        if connected:
            ref_context = "\n\nCONNECTED REFERENCES:\n" + "\n".join(
                f"- {r.get('authors','')} ({r.get('year','')}) {r.get('title','')}"
                for r in connected[:20]
            )

    # Load project framing
    framing = ""
    if project:
        proj_file = PROJECTS_DIR / (project + ".md")
        if proj_file.exists():
            try:
                pt  = proj_file.read_text(encoding="utf-8")
                pp  = pt.split("---", 2)
                if len(pp) >= 3 and "## Framing" in pp[2]:
                    raw = pp[2].split("## Framing")[1].split("\n## ")[0].strip()
                    if raw and not raw.startswith("<!--"):
                        framing = raw
            except Exception:
                pass

    framing_block = f"\nRESEARCH FRAMING:\n{framing}\n" if framing else ""
    scope        = f"project '{project}'" if project else "all sessions"
    session_text = "\n\n---\n\n".join(summaries)

    settings  = load_settings()
    local_cfg = settings.get("models", {}).get("local", {})
    _model_map = {
        "deepseek": local_cfg.get("reasoning",  "deepseek-r1:8b"),
        "qwen":     local_cfg.get("asia",       "qwen2.5:14b"),
        "mistral":  local_cfg.get("europe",     "mistral:7b"),
        "cohere":   local_cfg.get("canadian",   "command-r7b:latest"),
        "gemma":    local_cfg.get("multimodal", "gemma4:latest"),
        "llama":    local_cfg.get("general",    "llama3.1:8b"),
    }
    model_str = _model_map.get(req_model, local_cfg.get("reasoning", "deepseek-r1:8b"))

    lens_prompt = f"""You are a critical research supervisor reviewing a PhD researcher's work in progress.
Your job is NOT to summarise what is there — it is to find what is missing, what is weak, and what the researcher has not yet asked.
Be direct. Be specific. This is the most useful thing you can do.

Scope: {scope}
{framing_block}
Produce exactly five sections using these exact headers:

## UNASKED QUESTIONS
What important questions has this researcher not yet asked? What should they be investigating that they aren't?

## ARGUMENT WEAKNESSES
Where is the reasoning soft? What claims are made without sufficient support in the sessions?

## MISSING PERSPECTIVES
What disciplinary lenses, theoretical frameworks, or communities of practice are entirely absent from this inquiry?

## EXAMINER CHALLENGES
What would a skeptical dissertation examiner ask that this researcher has not yet addressed?

## NEXT MOVES
What are the three most important things this researcher should do next to strengthen their work?
{framing_block}
SESSIONS:
{session_text}{ref_context}"""

    try:
        synthesis = call_ollama(model_str, lens_prompt)
        return jsonify({"synthesis": synthesis, "session_count": matched, "project": project})
    except Exception as e:
        return jsonify({"error": str(e)}), 500


@app.route("/api/references/<ref_filename>/annotate", methods=["POST"])
def annotate_reference(ref_filename):
    data   = request.json or {}
    models = data.get("models", ["deepseek"])

    if "/" in ref_filename or "\\" in ref_filename or ".." in ref_filename:
        return jsonify({"error": "Invalid filename"}), 400
    filepath = (REFERENCES_DIR / ref_filename).resolve()
    if REFERENCES_DIR.resolve() not in filepath.parents:
        return jsonify({"error": "Invalid path"}), 400
    if not filepath.exists():
        return jsonify({"error": f"Reference file not found: {ref_filename}"}), 404

    text  = filepath.read_text(encoding="utf-8")
    parts = text.split("---", 2)
    if len(parts) < 3:
        return jsonify({"error": "Invalid canonical file format"}), 400

    meta = {}
    for line in parts[1].strip().splitlines():
        if ": " in line:
            k, v = line.split(": ", 1)
            meta[k.strip()] = v.strip()

    title   = meta.get("title", "Unknown")
    authors = meta.get("authors", "Unknown")
    year    = meta.get("year", "")
    themes  = meta.get("themes", "")

    existing_body = parts[2]
    existing_annotation = ""
    if "## Annotation" in existing_body:
        existing_annotation = existing_body.split("## Annotation")[1].split("##")[0].strip()
        if existing_annotation.startswith("<!--"):
            existing_annotation = ""

    annotation_prompt = f"""Read this academic reference and provide a concise critical annotation (100-150 words).
What does this source argue? What is its methodology? What are its limitations?

Title: {title}
Authors: {authors} ({year})
Themes: {themes}
{"Existing annotation: " + existing_annotation if existing_annotation else ""}

Provide a scholarly annotation suitable for a PhD research bibliography."""

    results = {}
    for model in models:
        try:
            _, result, error, _, _ = call_model(model, annotation_prompt)
            if result:
                results[model] = result
        except Exception as e:
            results[model] = f"Error: {e}"

    if not results:
        return jsonify({"error": "No models returned annotations"}), 500

    if len(results) > 1:
        synthesis = run_synthesis(annotation_prompt, results)
    else:
        synthesis = list(results.values())[0]

    voices = "\n\n".join(f"**{m.upper()}:** {r}" for m, r in results.items())
    new_annotation = f"<!-- Multi-voice annotation generated {datetime.now(datetime.UTC).strftime('%Y-%m-%d')} -->\n\n{voices}\n\n**SYNTHESIS:** {synthesis}"

    if "## Annotation" in existing_body:
        before = existing_body.split("## Annotation")[0]
        after_parts = existing_body.split("## Annotation")[1].split("\n## ", 1)
        after = ("\n## " + after_parts[1]) if len(after_parts) > 1 else ""
        new_body = before + "## Annotation\n" + new_annotation + after
    else:
        new_body = existing_body + "\n## Annotation\n" + new_annotation

    new_file = "---" + parts[1] + "---\n" + new_body
    filepath.write_text(new_file, encoding="utf-8")

    return jsonify({"status": "annotated", "filename": ref_filename, "models_used": list(results.keys()), "synthesis": synthesis})


@app.route("/api/ingest/scan-pdf-folder", methods=["POST"])
def scan_pdf_folder():
    """
    Scan ~/Documents/Research/PDFs/ for PDF files.
    For each file matching AuthorLastname_Year_ShortTitle.pdf naming convention,
    attempt text extraction via pdfplumber first.
    If extraction returns nothing (scanned/image PDF), flag for Gemma OCR.
    Creates reference stubs from filename + any extracted metadata.
    """
    import re
    pdf_dir = RESEARCH_PDF_DIR
    custom_path = (request.json or {}).get("path", "")
    if custom_path:
        pdf_dir = Path(custom_path).expanduser()

    if not pdf_dir.exists():
        return jsonify({"error": f"PDF folder not found: {pdf_dir}", "path": str(pdf_dir)}), 404

    results = {"scanned": 0, "imported": 0, "skipped": 0, "ocr_needed": [], "errors": []}
    existing_refs = {r.get("_filename", "") for r in read_all_references()}

    for pdf_path in sorted(pdf_dir.glob("*.pdf")):
        results["scanned"] += 1
        stem = pdf_path.stem  # AuthorLastname_Year_ShortTitle

        # Parse filename convention: Author_Year_Title
        parts = stem.split("_", 2)
        author = parts[0].strip() if len(parts) > 0 else ""
        year   = parts[1].strip() if len(parts) > 1 else ""
        title  = parts[2].replace("-", " ").replace("_", " ").strip() if len(parts) > 2 else stem

        # Validate year looks like a year
        if not re.match(r'^\d{4}$', year):
            year, title = "", stem  # filename doesn't follow convention — use whole stem as title

        # Skip if already in library (loose match on author+year)
        already_exists = any(
            author.lower() in fn.lower() and year in fn
            for fn in existing_refs
        )
        if already_exists:
            results["skipped"] += 1
            continue

        # Attempt text extraction
        text_extracted = ""
        needs_ocr = False
        try:
            import pdfplumber
            with pdfplumber.open(str(pdf_path)) as pdf:
                pages_text = []
                for page in pdf.pages[:3]:  # first 3 pages for metadata
                    t = page.extract_text()
                    if t:
                        pages_text.append(t)
                text_extracted = "\n".join(pages_text).strip()
        except Exception as e:
            results["errors"].append(f"{pdf_path.name}: pdfplumber error — {e}")

        if not text_extracted:
            needs_ocr = True
            results["ocr_needed"].append(pdf_path.name)

        # Build reference stub
        rec = {
            "title":             title,
            "authors":           author,
            "year":              year,
            "source_type":       "other",
            "url_doi":           "",
            "verification_status": "surfaced",
            "physical_holding":  "pdf",
            "holding_location":  str(pdf_path),
            "annotation":        text_extracted[:500] if text_extracted else "<!-- Scanned PDF — run Gemma OCR to extract content -->",
            "tags":              "pdf-import",
        }

        try:
            write_canonical_reference(rec)
            results["imported"] += 1
        except Exception as e:
            results["errors"].append(f"{pdf_path.name}: {e}")

    return jsonify({
        **results,
        "path": str(pdf_dir),
        "message": _scan_summary(results)
    })


def _scan_summary(r):
    parts = []
    if r["imported"]:   parts.append(f"{r['imported']} imported")
    if r["skipped"]:    parts.append(f"{r['skipped']} already in library")
    if r["ocr_needed"]: parts.append(f"{len(r['ocr_needed'])} need Gemma OCR")
    if r["errors"]:     parts.append(f"{len(r['errors'])} errors")
    return " · ".join(parts) if parts else "Nothing new found"


@app.route("/api/ingest/ocr", methods=["POST"])
def ocr_capture():
    """
    Run Gemma 4 OCR on an uploaded image or scanned PDF.
    Returns extracted text as a capture record.
    Saves to canonical/sessions/ as a capture file.
    """
    import base64

    file        = request.files.get("file")
    source_note = request.form.get("note", "")   # optional context from researcher
    mode        = request.form.get("mode", "typed")  # "typed" or "handwritten"
    if not file:
        return jsonify({"error": "No file uploaded"}), 400

    filename  = file.filename.lower()
    file_data = file.read()
    is_pdf    = filename.endswith(".pdf")
    is_image  = any(filename.endswith(ext) for ext in [".jpg", ".jpeg", ".png", ".webp", ".gif"])

    if not is_pdf and not is_image:
        return jsonify({"error": "Unsupported file type — use PDF, JPG, PNG, or WEBP"}), 400

    # For PDFs in typed mode: try pdfplumber text extraction first
    # In handwritten mode: skip pdfplumber entirely — go straight to Gemma
    if is_pdf and mode != "handwritten":
        try:
            import pdfplumber, io
            with pdfplumber.open(io.BytesIO(file_data)) as pdf:
                pages_text = []
                for page in pdf.pages:
                    t = page.extract_text()
                    if t:
                        pages_text.append(t)
                extracted = "\n".join(pages_text).strip()
            if extracted:
                # Typed PDF — no OCR needed
                capture = _write_capture(extracted, file.filename, source_note, method="pdfplumber")
                return jsonify({
                    "status":   "extracted",
                    "method":   "pdfplumber",
                    "message":  f"Text extracted — {len(pdf.pages)} pages",
                    "text":     extracted[:1000],
                    "capture":  capture,
                })
        except Exception:
            pass  # fall through to Gemma

    # Image or scanned PDF — send to Gemma 4 via Ollama multimodal
    try:
        import urllib.request as _ur
        settings  = load_settings()
        local_cfg = settings.get("models", {}).get("local", {})
        model_str = local_cfg.get("multimodal", "gemma4:latest")

        ocr_prompt = "Please transcribe all text visible in this image exactly as written. Preserve line breaks where meaningful. If handwritten, do your best — note any words you are uncertain about with [?]."
        if source_note:
            ocr_prompt += f"\n\nContext from researcher: {source_note}"

        def _gemma_ocr_image(image_b64):
            """Send a single image to Gemma and return transcribed text."""
            payload = json.dumps({
                "model":      model_str,
                "prompt":     ocr_prompt,
                "images":     [image_b64],
                "stream":     False,
                "keep_alive": 0
            }).encode()
            req = _ur.Request(
                f"{OLLAMA_BASE}/api/generate",
                data=payload,
                headers={"Content-Type": "application/json"}
            )
            with _ur.urlopen(req, timeout=120) as r:
                return json.loads(r.read()).get("response", "").strip()

        # Multi-page handwritten PDF — rasterize each page and OCR individually
        if is_pdf and mode == "handwritten":
            try:
                from pdf2image import convert_from_bytes
                import io as _io
                # poppler may not be on Flask's PATH (launchd strips Homebrew)
                # pass the explicit path so pdf2image can find pdftoppm
                import shutil, os
                poppler_path = shutil.which("pdftoppm") or "/opt/homebrew/bin"
                if poppler_path and poppler_path.endswith("pdftoppm"):
                    poppler_path = os.path.dirname(poppler_path)
                pages = convert_from_bytes(file_data, dpi=200, poppler_path=poppler_path)
                page_texts = []
                for i, page_img in enumerate(pages):
                    buf = _io.BytesIO()
                    page_img.save(buf, format="PNG")
                    b64 = base64.b64encode(buf.getvalue()).decode("utf-8")
                    text = _gemma_ocr_image(b64)
                    page_texts.append(f"--- Page {i+1} ---\n{text}")
                ocr_text = "\n\n".join(page_texts)
                page_count = len(pages)
                method_label = f"gemma-ocr-{page_count}p"
            except ImportError:
                return jsonify({"error": "pdf2image not installed — run: pip install pdf2image and brew install poppler"}), 500
        else:
            # Single image or single-page PDF
            b64 = base64.b64encode(file_data).decode("utf-8")
            ocr_text = _gemma_ocr_image(b64)
            method_label = "gemma-ocr"
            page_count = 1

        capture = _write_capture(ocr_text, file.filename, source_note, method=method_label)
        return jsonify({
            "status":  "ocr_complete",
            "method":  method_label,
            "message": f"Gemma OCR complete — {page_count} page(s)",
            "text":    ocr_text[:1000],
            "full_text": ocr_text,
            "capture": capture,
        })

    except Exception as e:
        import traceback
        return jsonify({"error": f"Gemma OCR failed: {e}", "detail": traceback.format_exc()}), 500


def _write_capture(text: str, source_filename: str, note: str, method: str) -> str:
    """Write a capture canonical file and return its filename."""
    capture_id = str(uuid.uuid4())
    timestamp  = datetime.now(datetime.UTC).strftime("%Y-%m-%d_%H-%M")
    filename   = f"capture_{timestamp}.md"
    canonical  = f"""---
id: {capture_id}
created_at: {datetime.now(datetime.UTC).isoformat()}
source_type: capture
capture_method: {method}
source_file: {source_filename}
status: raw-capture
---

## Source Note
{note or "<!-- Add context: where was this from, who wrote it, what situation? -->"}

## Extracted Text
{text}

## Your Annotation
<!-- What does this capture mean for your research? -->
"""
    filepath = SESSIONS_DIR / filename
    filepath.write_text(canonical, encoding="utf-8")
    return filename


@app.route("/api/notes", methods=["GET"])
def get_notes():
    notes = []
    for filepath in sorted(NOTES_DIR.glob("*.md"), reverse=True):
        try:
            text  = filepath.read_text(encoding="utf-8")
            parts = text.split("---", 2)
            if len(parts) >= 3:
                meta = {}
                for line in parts[1].strip().splitlines():
                    if ": " in line:
                        k, v = line.split(": ", 1)
                        meta[k.strip()] = v.strip()
                meta["_filename"] = filepath.name
                body = parts[2]
                def extract_note_section(body, heading):
                    if "## " + heading in body:
                        raw = body.split("## " + heading)[1].split("\n## ")[0].strip()
                        if raw and not raw.startswith("<!--"):
                            return raw
                    return ""
                meta["body"]        = extract_note_section(body, "What I'm sitting with")
                meta["questions"]   = extract_note_section(body, "Questions it raised")
                meta["connections"] = extract_note_section(body, "Connections I'm noticing")
                notes.append(meta)
        except Exception:
            pass
    return jsonify(notes)


@app.route("/api/notes", methods=["POST"])
def create_note():
    data     = request.json or {}
    title    = data.get("title", "").strip()
    if not title:
        return jsonify({"error": "Title required"}), 400
    note_id  = str(uuid.uuid4())
    slug     = "-".join(title.lower().split()[:5])
    slug     = "".join(c for c in slug if c.isalnum() or c == "-")
    timestamp = datetime.now(datetime.UTC).strftime("%Y-%m-%d_%H-%M")
    filename  = f"note_{timestamp}_{slug[:30]}.md"
    body      = data.get("body", "") or "<!-- What are you sitting with? -->"
    canonical = f"""---
id: {note_id}
title: {title}
source: {data.get("source", "")}
project: {data.get("project", "")}
writing: {data.get("writing", "")}
status: active
created_at: {datetime.now(datetime.UTC).isoformat()}
updated_at: {datetime.now(datetime.UTC).isoformat()}
---

## What I'm sitting with
{body}

## Questions it raised
<!-- Questions this reading or thought provoked -->

## Connections I'm noticing
<!-- Links to other ideas, sources, or threads -->
"""
    filepath = NOTES_DIR / filename
    filepath.write_text(canonical, encoding="utf-8")
    return jsonify({"status": "created", "filename": filename, "slug": slug})


@app.route("/api/notes/<note_filename>", methods=["PUT"])
def update_note(note_filename):
    if "/" in note_filename or "\\" in note_filename or ".." in note_filename:
        return jsonify({"error": "Invalid filename"}), 400
    filepath = (NOTES_DIR / note_filename).resolve()
    if not filepath.exists():
        return jsonify({"error": "Note not found"}), 404
    data  = request.json or {}
    text  = filepath.read_text(encoding="utf-8")
    parts = text.split("---", 2)
    if len(parts) < 3:
        return jsonify({"error": "Invalid format"}), 400
    meta = {}
    for line in parts[1].strip().splitlines():
        if ": " in line:
            k, v = line.split(": ", 1)
            meta[k.strip()] = v.strip()
    for field in ["title", "source", "project", "writing", "status"]:
        if field in data:
            meta[field] = data[field]
    meta["updated_at"] = datetime.now(datetime.UTC).isoformat()
    body = parts[2]
    def replace_note_section(body, heading, new_content):
        if not new_content:
            return body
        marker = "## " + heading
        if marker in body:
            before = body.split(marker)[0]
            rest   = body.split(marker)[1]
            after  = ("\n## " + rest.split("\n## ", 1)[1]) if "\n## " in rest else ""
            return before + marker + "\n" + new_content + "\n" + after
        return body.rstrip() + "\n\n" + marker + "\n" + new_content + "\n"
    if "body" in data:
        body = replace_note_section(body, "What I'm sitting with", data["body"])
    if "questions" in data:
        body = replace_note_section(body, "Questions it raised", data["questions"])
    if "connections" in data:
        body = replace_note_section(body, "Connections I'm noticing", data["connections"])
    fm_lines = "\n".join(f"{k}: {v}" for k, v in meta.items() if v is not None)
    filepath.write_text(f"---\n{fm_lines}\n---\n{body}", encoding="utf-8")
    return jsonify({"status": "updated"})


@app.route("/api/notes/<note_filename>", methods=["DELETE"])
def delete_note(note_filename):
    if "/" in note_filename or "\\" in note_filename or ".." in note_filename:
        return jsonify({"error": "Invalid filename"}), 400
    filepath = (NOTES_DIR / note_filename).resolve()
    if not filepath.exists():
        return jsonify({"error": "Note not found"}), 404
    filepath.unlink()
    return jsonify({"status": "deleted"})


def _lock_is_alive():
    """Return True if the current lock holder has heartbeated recently enough."""
    if not _session_lock["tab_id"]:
        return False
    return (_time.time() - _session_lock["last_beat"]) < SESSION_LOCK_TIMEOUT


@app.route("/api/session/claim", methods=["POST"])
def session_claim():
    """
    Called on page load. tab_id is a UUID generated by the browser.
    Returns:
      { "status": "claimed" }                            — this tab owns the session
      { "status": "readonly", "holder": tab_id_prefix } — another tab/device holds it
    Read-only: References, Notes, Intelligence browsing stay functional.
    Write operations (prompt, ingest, save & break) are blocked server-side.
    """
    tab_id = (request.json or {}).get("tab_id", "")
    if not tab_id:
        return jsonify({"error": "tab_id required"}), 400
    with _session_lock_mutex:
        if not _lock_is_alive() or _session_lock["tab_id"] == tab_id:
            _session_lock["tab_id"]     = tab_id
            _session_lock["claimed_at"] = _time.time()
            _session_lock["last_beat"]  = _time.time()
            return jsonify({"status": "claimed", "tab_id": tab_id})
        else:
            holder_prefix = (_session_lock["tab_id"] or "")[:8]
            return jsonify({"status": "readonly", "holder": holder_prefix}), 200


@app.route("/api/session/heartbeat", methods=["POST"])
def session_heartbeat():
    """Active tab pings every 20s to keep the lock alive."""
    tab_id = (request.json or {}).get("tab_id", "")
    with _session_lock_mutex:
        if _session_lock["tab_id"] == tab_id:
            _session_lock["last_beat"] = _time.time()
            return jsonify({"status": "ok"})
        return jsonify({"status": "lost"}), 200


@app.route("/api/session/takeover", methods=["POST"])
def session_takeover():
    """
    Explicit takeover — researcher moves from phone to laptop,
    or a crashed tab left a stale lock. Forces the lock regardless of holder.
    """
    tab_id = (request.json or {}).get("tab_id", "")
    if not tab_id:
        return jsonify({"error": "tab_id required"}), 400
    with _session_lock_mutex:
        _session_lock["tab_id"]     = tab_id
        _session_lock["claimed_at"] = _time.time()
        _session_lock["last_beat"]  = _time.time()
    return jsonify({"status": "claimed", "tab_id": tab_id})


@app.route("/api/session/release", methods=["POST"])
def session_release():
    """Called on beforeunload — releases lock cleanly when a tab closes."""
    tab_id = (request.json or {}).get("tab_id", "")
    with _session_lock_mutex:
        if _session_lock["tab_id"] == tab_id:
            _session_lock["tab_id"]     = None
            _session_lock["claimed_at"] = None
            _session_lock["last_beat"]  = None
    return jsonify({"status": "released"})


def _require_lock(tab_id):
    """
    Write-route guard. Returns a Flask error response if this tab doesn't
    hold the lock, or None if the write should proceed.
    """
    with _session_lock_mutex:
        if not _lock_is_alive():
            return None  # No live lock (e.g. after Flask restart) — allow
        if _session_lock["tab_id"] != tab_id:
            return jsonify({
                "error":   "readonly",
                "message": "Session is active on another device. Take over to write."
            }), 423
    return None


@app.route("/api/broadcast", methods=["GET"])
def get_broadcast():
    try:
        import urllib.request
        with urllib.request.urlopen(BROADCAST_URL, timeout=3) as r:
            data = json.loads(r.read())
            b = data.get("broadcast", {})
            if not b.get("active"): return jsonify({})
            expires = b.get("expires")
            if expires and datetime.fromisoformat(expires) < datetime.now(datetime.UTC): return jsonify({})
            return jsonify(b)
    except Exception:
        return jsonify({})


@app.route("/api/save-break", methods=["POST"])
def save_and_break():
    from utils.git_preflight import safe_commit
    tab_id   = (request.json or {}).get("tab_id", "")
    lock_err = _require_lock(tab_id)
    if lock_err:
        return lock_err
    message = request.json.get("message", f"Session — {datetime.now(datetime.UTC).strftime('%Y-%m-%d %H:%M')}")
    return jsonify(safe_commit(APP_ROOT, message))


@app.route("/assets/<path:filename>")
def serve_assets(filename):
    return send_from_directory(APP_ROOT / "assets", filename)


if __name__ == "__main__":
    port = int(os.environ.get("MARGINALIA_PORT", 5000))
    threading.Timer(1.5, lambda: webbrowser.open(f"http://localhost:{port}")).start()
    print(f"\n  Marginalia v1.4.1 running at http://localhost:{port}\n")
    print(f"  Keys loaded from: {'setup.env' if setup_env.exists() else '.env (legacy)'}\n")
    app.run(host="0.0.0.0", port=port, debug=False)
